<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Laragear\WebAuthn\Enums\Formats;

/**
 * Spec 008 T-01: webauthn_credentials (02-schema-delta.md).
 *
 * Column-for-column the schema Laragear's WebAuthnCredential::migration()
 * defines, with ONE deliberate substitution: the package's createMorph()
 * emits a bigint authenticatable_id (it assumes integer user keys), while
 * Vision Law users are UUIDs (spec 001). The morph is therefore declared
 * with uuidMorphs() so authenticatable_id is a uuid column. Recorded as
 * an implementation amendment in 02-schema-delta.md.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('webauthn_credentials', function (Blueprint $table) {
            // The PublicKeyCredential ID generated by the authenticator.
            $table->string('id', 510)->primary();

            $table->uuidMorphs('authenticatable', 'webauthn_user_index');

            // The anonymized WebAuthn user handle (UUID) — NOT our user
            // PK; the link to the user is the morph above (008-D08).
            $table->uuid('user_id');

            // Friendly name the user gives the credential (008-D10).
            $table->string('alias')->nullable();

            // Clone detection counter.
            $table->unsignedBigInteger('counter')->nullable();
            $table->string('rp_id');
            $table->string('origin');
            $table->json('transports')->nullable();
            $table->uuid('aaguid')->nullable();

            // The public key (encrypted at rest by the model cast, C-07).
            $table->text('public_key');
            $table->string('attestation_format')->default(Formats::None->value);
            $table->json('certificates')->nullable();

            $table->timestamp('disabled_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('webauthn_credentials');
    }
};
